#! /bin/zsh
source ~/dotfiles/zsh/variables.sh
source ~/dotfiles/zsh/aliases.sh
source ~/dotfiles/zsh/functions.sh
source ~/dotfiles/zsh/prompt.sh
source ~/dotfiles/zsh/keybind.sh

setopt hist_ignore_all_dups

setopt autocd
setopt correct_all
setopt AUTO_LIST
setopt AUTO_MENU
setopt LIST_AMBIGUOUS


# ZSH_THEME="robbyrussell"
CASE_SENSITIVE="true" # Case insensitive completion

ENABLE_CORRECTION="true" # Command autocorrection

autoload -U compinit
compinit

# DISABLE_UNTRACKED_FILES_DIRTY="true" #To make git addon faster for large repos

source ~/dotfiles/modules/zsh-autosuggestions/zsh-autosuggestions.zsh

# export LANG=en_US.UTF-8
export EDITOR='vim'

zstyle ':completion:*' special-dirs true

source ~/dotfiles/modules/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

__git_files () {
  _wanted files expl 'local files' _files
}
