
source ~/dotfiles/zsh/variables.sh
source ~/dotfiles/zsh/aliases.sh
source ~/dotfiles/zsh/functions.sh

setopt hist_ignore_all_dups

setopt autocd

export ZSH=~/.oh-my-zsh

# ZSH_THEME="robbyrussell"
CASE_SENSITIVE="false" # Case insensitive completion

DISABLE_AUTO_UPDATE="true" # No autoupdate off oh-my-zsh
ENABLE_CORRECTION="true" # Command autocorrection
# DISABLE_UNTRACKED_FILES_DIRTY="true" #To make git addon faster for large repos

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# export LANG=en_US.UTF-8
export EDITOR='vim'

function git_branch() {
git rev-parse --abbrev-ref HEAD > /dev/null 2>&1
if [[ $? == 0 ]] ; then
  echo -n "(`git rev-parse --abbrev-ref HEAD`)"
fi
}

PROMPT='%B%F{green}%n@%m %F{cyan}%~/ %F{red}`git_branch`
%F{yellow}%D{%H:%M}%}%b%k%f $ '
