#! /bin/zsh
source ~/dotfiles/zsh/variables.sh
source ~/dotfiles/zsh/aliases.sh
source ~/dotfiles/zsh/functions.sh
source ~/dotfiles/zsh/prompt.sh

setopt hist_ignore_all_dups

setopt autocd
setopt menu_complete


# ZSH_THEME="robbyrussell"
CASE_SENSITIVE="true" # Case insensitive completion

ENABLE_CORRECTION="true" # Command autocorrection

#autoload -U compaudit compinit

# DISABLE_UNTRACKED_FILES_DIRTY="true" #To make git addon faster for large repos

plugins=(
  zsh-autosuggestions #git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
)


# export LANG=en_US.UTF-8
export EDITOR='vim'

zstyle ':completion:*' special-dirs true

